### ISSUE TITLE
`dashmate reset --hard` throws error `Invalid Version: 19.03.13` (running `v0.20.0-dev.3`)

### ISSUE THREAD

**Issue by cloudwheels** [dashevo/dashmate#375] opened 2021-06-08 11:35 UTC
## Expected Behavior
Hard reset succeeds

## Current Behavior
Hard reset fails. Unclear as to what the Invalid Version number related to 

## Steps to Reproduce (for bugs)

`dashmate reset --hard && dashmate update`
```
❯ Reset base node
  ✖ Invalid Version: 19.03.13
  ◼ Remove all services and associated data
  ◼ Reset config base
```

## Context
Unable to reset dashmate config & data

## Your Environment

* Version used: v0.20.0-dev.3
* Environment name and version (e.g. Chrome 39, node.js 5.4): node.js v14.4.0
* Operating System and version (desktop, server, or mobile): Ubuntu [studio] 20.04
* Link to your project: N/A

**Comment by dashameter** [comment] 2021-09-07 18:13
@cloudwheels can you confirm if this issue is still current with v.20 on master branch or close it if it is fixed?

**Comment by strophy** [comment] 2021-09-10 10:39
Cannot reproduce on `v0.20` on current master branch. The version number you are seeing relates to Docker.

It looks like you modified the "base" config, but this is intended to be used as a template for user configs when creating your own network. You can use `dashmate config:list` to view configs for existing networks and `dashmate config:default` to select one of them, or `dashmate config:create` to create a new one. Alternatively, the `dashmate setup` command will interactively ask you a few questions and set the default config for you. I'm closing this because I can't reproduce, but feel free to reopen with more specific instructions to reproduce if necessary.

**Closed by strophy** 2021-09-10 10:39 UTC
Labels: bug
